require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tasks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Task. As you add validations to Task, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { title: "Ha Ling Peak", description: "Best Trail in Canmore", priority: 1 }
  }

  let(:invalid_attributes) {
    { description: "Best Trail in Canmore", priority: 1 }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Task.create! valid_attributes
      get tasks_url
      expect(response).to be_successful
      expect(response.body).to include("Ha Ling Peak")
    end

    it "shows no missing priorities if all tasks have priorities" do
      Task.create!(title: "Ha Ling Peak", description: "Best Trail in Canmore", priority: 1 )
      Task.create!(title: "Ha Ling Peak2", description: "Best Trail in Canmore2", priority: 2 )
      get tasks_url
      expect(response).to be_successful
      expect(response.body).to include("<p>Missing Priorities: </p>")
    end

    it "shows the proper missing priority if there is at least one task with a priority" do
      Task.create!(title: "Ha Ling Peak", description: "Best Trail in Canmore" )
      Task.create!(title: "Ha Ling Peak2", description: "Best Trail in Canmore2", priority: 2 )
      get tasks_url
      expect(response).to be_successful
      expect(response.body).to include("<p>Missing Priorities: 1 </p>")

      Task.create!(title: "Ha Ling Peak2", description: "Best Trail in Canmore2", priority: 5 )
      get tasks_url
      expect(response.body).to include("<p>Missing Priorities: 1 3 4 </p>")
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      task = Task.create! valid_attributes
      get task_url(task)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_task_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      task = Task.create! valid_attributes
      get edit_task_url(task)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Task" do
        expect {
          post tasks_url, params: { task: valid_attributes }
        }.to change(Task, :count).by(1)
      end

      it "redirects to the created task" do
        post tasks_url, params: { task: valid_attributes }
        expect(response).to redirect_to(tasks_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Task" do
        expect {
          post tasks_url, params: { task: invalid_attributes }
        }.to change(Task, :count).by(0)
      end

      it "renders an unsuccessful response" do
        post tasks_url, params: { task: invalid_attributes }
        expect(response).to_not be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { title: "Go to East End of Rundle", description: "Very technical scree", priority: 2 }
      }

      it "updates the requested task" do
        task = Task.create! valid_attributes
        patch task_url(task), params: { task: new_attributes }
        task.reload
        expect(task.title).to_not eq("Ha Ling Peak")
        expect(task.title).to eq("Go to East End of Rundle")
      end

      it "redirects to the task" do
        task = Task.create! valid_attributes
        patch task_url(task), params: { task: new_attributes }
        task.reload
        expect(response).to redirect_to(task_url(task))
      end
    end

    context "with invalid parameters" do
      it "renders an unsuccessful response" do
        task = Task.create! valid_attributes
        patch task_url(task), params: { task: invalid_attributes }
        expect(response).to_not be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested task" do
      task = Task.create! valid_attributes
      expect {
        delete task_url(task)
      }.to change(Task, :count).by(-1)
    end

    it "redirects to the tasks list" do
      task = Task.create! valid_attributes
      delete task_url(task)
      expect(response).to redirect_to(tasks_url)
    end
  end
end
